import { FC } from 'react';
import { KeyRisk } from '../../../../types';
import RiskCard from './RiskCard';
import { AlertTriangle } from 'lucide-react';

const KeyRisksSection: FC<{ risks: KeyRisk[] }> = ({ risks }) => (
  <div className="space-y-6">
    <div className="flex items-center gap-3">
        <AlertTriangle className="h-8 w-8 text-primary"/>
        <div>
            <h2 className="text-2xl font-bold text-white">AI-Identified Key Risks</h2>
            <p className="text-secondary mt-1">Generated by analyzing all documents in the project's Virtual Data Room.</p>
        </div>
    </div>
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {risks.map((risk, index) => (
        <RiskCard key={index} risk={risk} />
      ))}
    </div>
  </div>
);

export default KeyRisksSection;
